name: Linux C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: build
      run: gcc main.c -o main.exe
    - id: Run
      run: ./main.exe
